# Generated by Django 6.0.3 on 2026-03-10 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('annee', models.IntegerField(choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3'), (4, 'Année 4'), (5, 'Année 5')], default=1)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='etudiants.filiere')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Note minimale : 0'), django.core.validators.MaxValueValidator(20.0, 'Note maximale : 20')])),
                ('semestre', models.CharField(default='S1', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-date', 'matiere'],
            },
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['nom', 'prenom'], name='etudiants_e_nom_bfd473_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['filiere', 'annee'], name='etudiants_e_filiere_201b04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'semestre')},
        ),
    ]
